### PR TITLE
Modify profile for LAX

### PR DESCRIPTION
**Pull request by leslieonline27**
This PR attempts to modify the configuration for the LAX profile for Linode Object Storage

### CODE REVIEW

**Comment by dkocher** [comment]
According to the [documentation](https://techdocs.akamai.com/cloud-computing/docs/object-storage#availability) from Linode the region for _Los Angeles, CA (USA)_ is `us-lax-1`. Let us know about your motivation to change this.

**Comment by leslieonline27** [comment]
This was actually an initial PR to validate what a region change would look like in Cyberduck.  Akamai will be changing all of the current regions and adding new ones as we release new high performance endpoints for Object Storage, for which multiple types may exist in a single region.  The documentation will also be changing at the same time as the release of these new endpoints

**Comment by dkocher** [comment]
> This was actually an initial PR to validate what a region change would look like in Cyberduck. Akamai will be changing all of the current regions and adding new ones as we release new high performance endpoints for Object Storage, for which multiple types may exist in a single region. The documentation will also be changing at the same time as the release of these new endpoints

Please reopen the PR when ready or mark as a draft. Approved pull requests will cause connection profiles to be deployed instantly.

**Comment by leslieonline27** [comment]
ok understood - are you able to confirm what the behaviour would be for a user of an existing profile in Cyberduck that is modified in this way?

**Comment by dkocher** [comment]
> ok understood - are you able to confirm what the behaviour would be for a user of an existing profile in Cyberduck that is modified in this way?

Previously installed connection profiles are only updated when the user opens _Preferences → Profiles_. This will update the version previously activated. Therefore you should ensure that a connection profile previously published does not cease working.

**Comment by leslieonline27** [comment]
ok great understood - thanks for you help clarifying.  We'll open a draft PR and will request a merge at the appropriate time

**Pull request closed without merging**
