### PR TITLE
Resolves #32

### LINKED ISSUE #32: Add connection profile for Synology C2 Object Storage
We would like to add profiles for Synology C2 Object Storage. This is an S3-compatible endpoint.

https://c2.synology.com/en-global/object-storage/overview
https://kb.synology.com/en-global/C2/tutorial/C2_Object_Storage_Introduction

### PR DESCRIPTION
**Pull request by BakaWang**
Add Synology C2 Object Storage profiles

### CODE REVIEW

**Comment by dkocher** [comment]
Do you want to add a [custom disk icon](https://docs.cyberduck.io/protocols/profiles/#disk-icon-template) to the profile?

**Comment by BakaWang** [comment]
OK, we will add a custom disk icon.

**Comment by dkocher** [comment]
> OK, we will add a custom disk icon.

Any success in designing a disk icon?

**Comment by BakaWang** [comment]
> Any success in designing a disk icon?

Icon added. Please continue the review, thank you.

**Review by dkocher — APPROVED** [review]

**Pull request merged**
